# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file

#exporters:
#  clickhouse:
#     endpoint: tcp://clickhouse:9000?dial_timeout=10s&compress=lz4&async_insert=1
#     ttl: 72h
#     traces_table_name: otel_traces
#     logs_table_name: otel_logs
#     create_schema: true
#     timeout: 5s
#     database: default
#     retry_on_failure:
#       enabled: true
#       initial_interval: 5s
#       max_interval: 30s
#       max_elapsed_time: 300s

# processors:
#   batch:
#     timeout: 5s
#     send_batch_size: 5000

# service:
#   pipelines:
#     traces:
#       receivers: [otlp]
#       processors: [batch]
#       exporters: [clickhouse]
#     logs:
#       receivers: [otlp]
#       processors: [batch]
#       exporters: [clickhouse]
